ALTER TABLE produto
    ADD COLUMN codigo_marca TEXT NOT NULL DEFAULT '',
    ADD COLUMN codigo_receita TEXT NOT NULL DEFAULT '',
    ADD COLUMN codigo_barra_novartis TEXT NOT NULL DEFAULT '',
    ADD COLUMN usa_grade BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN preco_custo_anterior NUMERIC(18,6) NOT NULL DEFAULT 0,
    ADD COLUMN preco_venda_anterior NUMERIC(18,6) NOT NULL DEFAULT 0,
    ADD COLUMN preco_farma_pop NUMERIC(18,6) NOT NULL DEFAULT 0,
    ADD COLUMN aliquota_pis NUMERIC(18,6) NOT NULL DEFAULT 0,
    ADD COLUMN aliquota_cofins NUMERIC(18,6) NOT NULL DEFAULT 0,
    ADD COLUMN pfcp NUMERIC(18,6) NOT NULL DEFAULT 0,
    ADD COLUMN pfcpst NUMERIC(18,6) NOT NULL DEFAULT 0;
